// <auto-generated />
using System;
using AiEmployee.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiEmployee.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiEmployeeDbContext))]
    [Migration("20260405121838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Behavior", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationRules")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AutomationRulesJson");

                    b.Property<bool>("ExcludeCommandsFromJudgeContext")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgeCommandPrefix")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("JudgeContextMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JudgePerMessageMaxChars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnboardingFirstMessageOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Behaviors", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BehaviorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIntegrationId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LanguageProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorId");

                    b.HasIndex("LanguageProfileId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Channel", "ExternalIntegrationId")
                        .IsUnique();

                    b.ToTable("Bots", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.LanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceFollowUpQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Formality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenericErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeNoConversationMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeNotEnoughContextMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeResultTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadThanksMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingGoalQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivationMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Locale");

                    b.ToTable("LanguageProfiles", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationSchema")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ClassificationSchemaJson");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Judgment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Judgments", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Lead", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Potential")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Behavior", b =>
                {
                    b.OwnsOne("AiEmployee.Domain.BotConfiguration.LeadFlow", "LeadFlow", b1 =>
                        {
                            b1.Property<Guid>("BehaviorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AnswerKeys")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AnswerKeysJson");

                            b1.Property<int?>("CaptureIndex")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LeadCaptureIndex");

                            b1.Property<int?>("FollowUpIndex")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LeadFollowUpIndex");

                            b1.HasKey("BehaviorId");

                            b1.ToTable("Behaviors");

                            b1.WithOwner()
                                .HasForeignKey("BehaviorId");
                        });

                    b.Navigation("LeadFlow")
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Bot", b =>
                {
                    b.HasOne("AiEmployee.Domain.BotConfiguration.Behavior", null)
                        .WithMany()
                        .HasForeignKey("BehaviorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.BotConfiguration.LanguageProfile", null)
                        .WithMany()
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.BotConfiguration.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Persona", b =>
                {
                    b.OwnsOne("AiEmployee.Domain.BotConfiguration.PromptSections", "Prompts", b1 =>
                        {
                            b1.Property<Guid>("PersonaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Judge")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("JudgePrompt");

                            b1.Property<string>("Lead")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LeadPrompt");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SystemPrompt");

                            b1.HasKey("PersonaId");

                            b1.ToTable("Personas");

                            b1.WithOwner()
                                .HasForeignKey("PersonaId");
                        });

                    b.Navigation("Prompts")
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Judgment", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Lead", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Message", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
