// <auto-generated />
using System;
using AiEmployee.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AiEmployee.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(AiEmployeePostgresDbContext))]
    partial class AiEmployeePostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Behavior", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutomationRules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AutomationRulesJson");

                    b.Property<bool>("EnableChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableJudge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableLead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ExcludeCommandsFromJudgeContext")
                        .HasColumnType("boolean");

                    b.Property<string>("HotLeadPotentialValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HotLeadTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JudgeCommandPrefix")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("JudgeContextMessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("JudgeInstruction")
                        .HasColumnType("text");

                    b.Property<int>("JudgePerMessageMaxChars")
                        .HasColumnType("integer");

                    b.Property<string>("JudgeSchemaJson")
                        .HasColumnType("text");

                    b.Property<string>("LeadInstruction")
                        .HasColumnType("text");

                    b.Property<string>("LeadSchemaJson")
                        .HasColumnType("text");

                    b.Property<bool>("OnboardingFirstMessageOnly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Behaviors", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BehaviorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalIntegrationId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorId");

                    b.HasIndex("LanguageProfileId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Channel", "ExternalIntegrationId")
                        .IsUnique();

                    b.ToTable("Bots", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.BotIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("Channel", "ExternalId")
                        .IsUnique();

                    b.ToTable("BotIntegrations", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.LanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExperienceFollowUpQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Formality")
                        .HasColumnType("integer");

                    b.Property<string>("GenericErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JudgeNoConversationMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JudgeNotEnoughContextMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JudgeResultTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadThanksMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OnboardingGoalQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReactivationMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Locale");

                    b.ToTable("LanguageProfiles", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassificationSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ClassificationSchemaJson");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PromptType")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId", "PromptType", "Version")
                        .IsUnique();

                    b.ToTable("PromptVersions", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Judgment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Judgments", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Lead", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Potential")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Speaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.ProcessedTelegramUpdate", b =>
                {
                    b.Property<string>("BotScopeKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("TelegramUpdateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BotScopeKey", "TelegramUpdateId");

                    b.ToTable("ProcessedTelegramUpdates", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("double precision");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("MessagesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.Settings.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Infrastructure.Persistence.Entities.MessageEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageEmbeddings", (string)null);
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Behavior", b =>
                {
                    b.OwnsOne("AiEmployee.Domain.BotConfiguration.EngagementRules", "EngagementRules", b1 =>
                        {
                            b1.Property<Guid>("BehaviorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ActiveMessageThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("EngagementActiveMessageThreshold");

                            b1.Property<double>("EngagementNormalizationFactor")
                                .HasColumnType("double precision")
                                .HasColumnName("EngagementNormalizationFactor");

                            b1.Property<double>("HighEngagementScoreThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("EngagementHighEngagementScoreThreshold");

                            b1.Property<int>("InactiveHoursThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("EngagementInactiveHoursThreshold");

                            b1.Property<int>("NewUserWindowHours")
                                .HasColumnType("integer")
                                .HasColumnName("EngagementNewUserWindowHours");

                            b1.Property<string>("StickyTags")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EngagementStickyTagsJson");

                            b1.HasKey("BehaviorId");

                            b1.ToTable("Behaviors");

                            b1.WithOwner()
                                .HasForeignKey("BehaviorId");
                        });

                    b.OwnsOne("AiEmployee.Domain.BotConfiguration.LeadFlow", "LeadFlow", b1 =>
                        {
                            b1.Property<Guid>("BehaviorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnswerKeys")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AnswerKeysJson");

                            b1.Property<int?>("CaptureIndex")
                                .HasColumnType("integer")
                                .HasColumnName("LeadCaptureIndex");

                            b1.Property<int?>("FollowUpIndex")
                                .HasColumnType("integer")
                                .HasColumnName("LeadFollowUpIndex");

                            b1.HasKey("BehaviorId");

                            b1.ToTable("Behaviors");

                            b1.WithOwner()
                                .HasForeignKey("BehaviorId");
                        });

                    b.Navigation("EngagementRules")
                        .IsRequired();

                    b.Navigation("LeadFlow")
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Bot", b =>
                {
                    b.HasOne("AiEmployee.Domain.BotConfiguration.Behavior", null)
                        .WithMany()
                        .HasForeignKey("BehaviorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.BotConfiguration.LanguageProfile", null)
                        .WithMany()
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.BotConfiguration.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.BotIntegration", b =>
                {
                    b.HasOne("AiEmployee.Domain.BotConfiguration.Bot", null)
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.Persona", b =>
                {
                    b.OwnsOne("AiEmployee.Domain.BotConfiguration.PromptSections", "Prompts", b1 =>
                        {
                            b1.Property<Guid>("PersonaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Judge")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("JudgePrompt");

                            b1.Property<string>("Lead")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LeadPrompt");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SystemPrompt");

                            b1.HasKey("PersonaId");

                            b1.ToTable("Personas");

                            b1.WithOwner()
                                .HasForeignKey("PersonaId");
                        });

                    b.Navigation("Prompts")
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.BotConfiguration.PromptVersion", b =>
                {
                    b.HasOne("AiEmployee.Domain.BotConfiguration.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Judgment", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiEmployee.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Lead", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Message", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiEmployee.Infrastructure.Persistence.Entities.MessageEmbeddingEntity", b =>
                {
                    b.HasOne("AiEmployee.Domain.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AiEmployee.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
